const char* ERROR_OPENING_DEVICE = "ERROR_OPENING_DEVICE";
const char* ERROR_ACQUIRING_SLAVE = "ERROR_ACQUIRING_SLAVE";
const char* ERROR_WRITING_TO_SLAVE = "ERROR_WRITING_TO_SLAVE";
const char* ERROR_READING_FULL_BUFFER = "ERROR_READING_FULL_BUFFER";
const char* ERROR_INTERACTING_WITH_DRIVER = "ERROR_INTERACTING_WITH_DRIVER";

const char* ARGUMENT_ERROR = "ARGUMENT_ERROR";
const char* UNKNOWN_ERROR = "UNKNOWN_ERROR";
const char* ERROR_TRANSLATING_STRUCT_TO_NODE =
    "ERROR_TRANSLATING_STRUCT_TO_NODE";
const char* ERROR_TRANSLATING_NODE_TO_STRUCT =
    "ERROR_TRANSLATING_NODE_TO_STRUCT";
const char* ERROR_CREATING_NAPI_VALUE = "ERROR_CREATING_NAPI_VALUE";
const char* REF_ERROR = "REF_ERROR";
const char* SENSOR_REPORT_ERROR = "SENSOR_REPORT_ERROR";

const char* ERROR_EXECUTING_TEST = "ERROR_EXECUTING_TEST";
const char* ASSERT_ERROR = "ASSERT_ERROR";
